# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("LazyCall"); if VERSION > v"0.6.0-dev"; Pkg.test("LazyCall"; coverage=true); else; Pkg.test("LazyCall"); end;'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("LazyCall")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # build documentation
  - julia -e 'Pkg.add("Documenter"); joinpath(Pkg.dir("LazyCall"), "docs", "make.jl") |> include'
